Enable jest testing
packages.json:
* Add enzyme and adapter to dev dependencies
* Remove jest from dev dependencies. This is currently included by ultra-responsive-calendar#react-scripts. Naming it in this repo's package.json too caused an error `TypeError: environment.setup is not a function`.
* Remove `jest.testEnvironment: "node"`; allow it to fall through to the default (browser) environment.
* Configure jest with a `moduleNameMapper`, that mocks out imported *.svg files.
* Configure jest with a `setupTestFrameworkScriptFile` file, that configures enzyme